(() => {
 const $=id=>document.getElementById(id), main=document.querySelector('main'), command=document.querySelector('.commandBar');
 const top=main?.querySelector(':scope > .top'), stats=main?.querySelector(':scope > .stats');
 const overviewMap=$('overviewMap')?.closest('section'), quick=overviewMap?.nextElementSibling;
 const hiddenCompat=[...main.querySelectorAll(':scope > section')].find(x=>x.style.display==='none');
 const modules={overview:[top,stats,overviewMap,quick,$('intelligencePanel')],data:[$('source'),$('historyPanel')],detect:[$('detect')],probability:[$('probability')],spatial:[$('mapSection')],temporal:[$('temporalLab')],compare:[$('compare')],map:[$('mapSection')],anomalies:[$('anomalies')],sources:[$('source'),$('live'),$('historyPanel')],report:[$('exports')],settings:[$('settingsPanel')],connections:[$('live')],help:[$('helpPanel')]};
 const labels={overview:['Overview','Your operational geospatial intelligence workspace.'],data:['Data','Validate, inspect and manage geospatial sources.'],detect:['Detect','Configure and execute the Meridian anomaly engine.'],probability:['Probability','Distribution fitting, Gaussian quadrature and differential diagnostics.'],spatial:['Spatial Intelligence','Explore spatial structure, neighbourhood effects and anomaly geography.'],temporal:['Temporal Intelligence','Inspect temporal validation and change behaviour for the active analysis.'],compare:['Compare','Compare variables, fit quality and anomaly methods.'],map:['Map','Explore Meridian findings geographically at 90, 95 and 99 percentiles.'],anomalies:['Anomalies','Explain why individual observations were classified as anomalous.'],sources:['Data Sources','Files, NASA FIRMS, Open-Meteo and external connections.'],report:['Report & Export','Package results for GIS, QGIS, analysis and reproducibility.'],settings:['Settings','Workspace behaviour and analysis defaults.'],connections:['API Connections','Manage live real-world data integrations.'],help:['Help','Understand Meridian scores, workflow and outputs.']};
 const all=[...new Set(Object.values(modules).flat().filter(Boolean))];
 const header=document.createElement('div'); header.id='moduleHeader'; header.className='moduleHeader'; header.innerHTML='<div class="eyebrow">MERIDIAN</div><h1 id="moduleTitle"></h1><div class="muted" id="moduleSubtitle"></div>'; command?.insertAdjacentElement('afterend',header);
 function show(view,push=true){view=modules[view]?view:'overview';all.forEach(el=>el.style.display='none');modules[view].filter(Boolean).forEach(el=>el.style.display='');if(hiddenCompat)hiddenCompat.style.display='none';header.style.display=view==='overview'?'none':'block';if(view!=='overview'){ $('moduleTitle').textContent=labels[view][0];$('moduleSubtitle').textContent=labels[view][1] }document.querySelectorAll('.nav a[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===view));document.body.dataset.view=view;if(push)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>{if((view==='map'||view==='spatial')&&window.map)window.map.invalidateSize();if(view==='overview'&&window.overviewMap)window.overviewMap.invalidateSize()},80)}
 document.querySelectorAll('.nav a[data-view]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();show(a.dataset.view)},true));
 window.meridianShow=show;
 window.meridianOpenAnalysis=async id=>{try{$('status').textContent='Opening saved analysis…';const r=await fetch('/jobs/'+encodeURIComponent(id)+'/result');if(!r.ok)throw new Error('Saved runtime result is unavailable');const payload=await r.json();if(typeof window.render==='function')window.render(payload);show('overview');$('status').textContent='Saved analysis opened.'}catch(e){$('status').textContent='Could not reopen analysis: '+e.message}};
 show((location.hash||'#overview').slice(1),false);
})();